package uk.gov.pay.adminusers.resources;
public class UserResourceGetMultipleIT extends uk.gov.pay.adminusers.resources.IntegrationTest {
    @org.junit.jupiter.api.Test
    public void shouldReturnMultipleUsers_whenGetUsersWithMultipleIds() {
        java.lang.String gatewayAccount1 = java.lang.String.valueOf(org.apache.commons.lang3.RandomUtils.nextInt());
        java.lang.String gatewayAccount2 = java.lang.String.valueOf(org.apache.commons.lang3.RandomUtils.nextInt());
        uk.gov.pay.adminusers.model.Service service = uk.gov.pay.adminusers.fixtures.ServiceDbFixture.serviceDbFixture(databaseHelper).withGatewayAccountIds(gatewayAccount1, gatewayAccount2).insertService();
        java.lang.String serviceExternalId = service.getExternalId();
        uk.gov.pay.adminusers.model.Role role = uk.gov.pay.adminusers.fixtures.RoleDbFixture.roleDbFixture(databaseHelper).insertRole();
        java.lang.String username1 = uk.gov.pay.adminusers.app.util.RandomIdGenerator.randomUuid();
        java.lang.String email1 = username1 + "@example.com";
        uk.gov.pay.adminusers.model.User user1 = uk.gov.pay.adminusers.fixtures.UserDbFixture.userDbFixture(databaseHelper).withServiceRole(service.getId(), role.getId()).withUsername(username1).withEmail(email1).insertUser();
        java.lang.String username2 = uk.gov.pay.adminusers.app.util.RandomIdGenerator.randomUuid();
        java.lang.String email2 = username2 + "@example.com";
        uk.gov.pay.adminusers.model.User user2 = uk.gov.pay.adminusers.fixtures.UserDbFixture.userDbFixture(databaseHelper).withServiceRole(service.getId(), role.getId()).withUsername(username2).withEmail(email2).insertUser();
        givenSetup().when().contentType(io.restassured.http.ContentType.JSON).accept(io.restassured.http.ContentType.JSON).get((((uk.gov.pay.adminusers.resources.UserResource.USERS_RESOURCE + "?ids=") + user1.getExternalId()) + ",") + user2.getExternalId()).then().statusCode(200).body("[0].external_id", org.hamcrest.core.Is.is(user1.getExternalId())).body("[0].username", org.hamcrest.core.Is.is(user1.getUsername())).body("[0].password", org.hamcrest.Matchers.nullValue()).body("[0].email", org.hamcrest.core.Is.is(user1.getEmail())).body("[0].service_roles", org.hamcrest.Matchers.hasSize(1)).body("[0].service_roles[0].service.external_id", org.hamcrest.core.Is.is(serviceExternalId)).body("[0].service_roles[0].service.name", org.hamcrest.core.Is.is(service.getName())).body("[0].telephone_number", org.hamcrest.core.Is.is(user1.getTelephoneNumber())).body("[0].otp_key", org.hamcrest.core.Is.is(user1.getOtpKey())).body("[0].login_counter", org.hamcrest.core.Is.is(0)).body("[0].disabled", org.hamcrest.core.Is.is(false)).body("[0].service_roles[0].role.name", org.hamcrest.core.Is.is(role.getName())).body("[0].service_roles[0].role.description", org.hamcrest.core.Is.is(role.getDescription())).body("[0].service_roles[0].role.permissions", org.hamcrest.Matchers.hasSize(role.getPermissions().size())).body("[0]._links", org.hamcrest.Matchers.hasSize(1)).body("[0]._links[0].href", org.hamcrest.core.Is.is("http://localhost:8080/v1/api/users/" + user1.getExternalId())).body("[0]._links[0].method", org.hamcrest.core.Is.is("GET")).body("[0]._links[0].rel", org.hamcrest.core.Is.is("self")).body("[1].external_id", org.hamcrest.core.Is.is(user2.getExternalId())).body("[1].username", org.hamcrest.core.Is.is(user2.getUsername())).body("[1].password", org.hamcrest.Matchers.nullValue()).body("[1].email", org.hamcrest.core.Is.is(user2.getEmail())).body("[1].service_roles", org.hamcrest.Matchers.hasSize(1)).body("[1].service_roles[0].service.external_id", org.hamcrest.core.Is.is(serviceExternalId)).body("[1].service_roles[0].service.name", org.hamcrest.core.Is.is(service.getName())).body("[1].telephone_number", org.hamcrest.core.Is.is(user2.getTelephoneNumber())).body("[1].otp_key", org.hamcrest.core.Is.is(user2.getOtpKey())).body("[1].login_counter", org.hamcrest.core.Is.is(0)).body("[1].disabled", org.hamcrest.core.Is.is(false)).body("[1].service_roles[0].role.name", org.hamcrest.core.Is.is(role.getName())).body("[1].service_roles[0].role.description", org.hamcrest.core.Is.is(role.getDescription())).body("[1].service_roles[0].role.permissions", org.hamcrest.Matchers.hasSize(role.getPermissions().size())).body("[1]._links", org.hamcrest.Matchers.hasSize(1)).body("[1]._links[0].href", org.hamcrest.core.Is.is("http://localhost:8080/v1/api/users/" + user2.getExternalId())).body("[1]._links[0].method", org.hamcrest.core.Is.is("GET")).body("[1]._links[0].rel", org.hamcrest.core.Is.is("self")).body("size()", org.hamcrest.core.Is.is(2));
    }

    @org.junit.jupiter.api.Test
    public void shouldReturnMultipleUsers_whenGetUsersWithMultipleIds_whenIdsAreRepeated() {
        java.lang.String gatewayAccount1 = java.lang.String.valueOf(org.apache.commons.lang3.RandomUtils.nextInt());
        java.lang.String gatewayAccount2 = java.lang.String.valueOf(org.apache.commons.lang3.RandomUtils.nextInt());
        uk.gov.pay.adminusers.model.Service service = uk.gov.pay.adminusers.fixtures.ServiceDbFixture.serviceDbFixture(databaseHelper).withGatewayAccountIds(gatewayAccount1, gatewayAccount2).insertService();
        java.lang.String serviceExternalId = service.getExternalId();
        uk.gov.pay.adminusers.model.Role role = uk.gov.pay.adminusers.fixtures.RoleDbFixture.roleDbFixture(databaseHelper).insertRole();
        java.lang.String username1 = uk.gov.pay.adminusers.app.util.RandomIdGenerator.randomUuid();
        java.lang.String email1 = username1 + "@example.com";
        uk.gov.pay.adminusers.model.User user1 = uk.gov.pay.adminusers.fixtures.UserDbFixture.userDbFixture(databaseHelper).withServiceRole(service.getId(), role.getId()).withUsername(username1).withEmail(email1).insertUser();
        givenSetup().when().contentType(io.restassured.http.ContentType.JSON).accept(io.restassured.http.ContentType.JSON).get((((uk.gov.pay.adminusers.resources.UserResource.USERS_RESOURCE + "?ids=") + user1.getExternalId()) + ",") + user1.getExternalId()).then().statusCode(200).body("[0].external_id", org.hamcrest.core.Is.is(user1.getExternalId())).body("[0].username", org.hamcrest.core.Is.is(user1.getUsername())).body("[0].password", org.hamcrest.Matchers.nullValue()).body("[0].email", org.hamcrest.core.Is.is(user1.getEmail())).body("[0].service_roles", org.hamcrest.Matchers.hasSize(1)).body("[0].service_roles[0].service.external_id", org.hamcrest.core.Is.is(serviceExternalId)).body("[0].service_roles[0].service.name", org.hamcrest.core.Is.is(service.getName())).body("[0].telephone_number", org.hamcrest.core.Is.is(user1.getTelephoneNumber())).body("[0].otp_key", org.hamcrest.core.Is.is(user1.getOtpKey())).body("[0].login_counter", org.hamcrest.core.Is.is(0)).body("[0].disabled", org.hamcrest.core.Is.is(false)).body("[0].service_roles[0].role.name", org.hamcrest.core.Is.is(role.getName())).body("[0].service_roles[0].role.description", org.hamcrest.core.Is.is(role.getDescription())).body("[0].service_roles[0].role.permissions", org.hamcrest.Matchers.hasSize(role.getPermissions().size())).body("[0]._links", org.hamcrest.Matchers.hasSize(1)).body("[0]._links[0].href", org.hamcrest.core.Is.is("http://localhost:8080/v1/api/users/" + user1.getExternalId())).body("[0]._links[0].method", org.hamcrest.core.Is.is("GET")).body("[0]._links[0].rel", org.hamcrest.core.Is.is("self")).body("size()", org.hamcrest.core.Is.is(1));
    }

    @org.junit.jupiter.api.Test
    public void shouldReturnSingleUser_whenGetUsersWithSingleId() {
        java.lang.String gatewayAccount1 = java.lang.String.valueOf(org.apache.commons.lang3.RandomUtils.nextInt());
        java.lang.String gatewayAccount2 = java.lang.String.valueOf(org.apache.commons.lang3.RandomUtils.nextInt());
        uk.gov.pay.adminusers.model.Service service = uk.gov.pay.adminusers.fixtures.ServiceDbFixture.serviceDbFixture(databaseHelper).withGatewayAccountIds(gatewayAccount1, gatewayAccount2).insertService();
        java.lang.String serviceExternalId = service.getExternalId();
        uk.gov.pay.adminusers.model.Role role = uk.gov.pay.adminusers.fixtures.RoleDbFixture.roleDbFixture(databaseHelper).insertRole();
        java.lang.String username = uk.gov.pay.adminusers.app.util.RandomIdGenerator.randomUuid();
        java.lang.String email = username + "@example.com";
        uk.gov.pay.adminusers.model.User user = uk.gov.pay.adminusers.fixtures.UserDbFixture.userDbFixture(databaseHelper).withServiceRole(service.getId(), role.getId()).withUsername(username).withEmail(email).insertUser();
        givenSetup().when().contentType(io.restassured.http.ContentType.JSON).accept(io.restassured.http.ContentType.JSON).get((uk.gov.pay.adminusers.resources.UserResource.USERS_RESOURCE + "?ids=") + user.getExternalId()).then().statusCode(200).body("[0].external_id", org.hamcrest.core.Is.is(user.getExternalId())).body("[0].username", org.hamcrest.core.Is.is(user.getUsername())).body("[0].password", org.hamcrest.Matchers.nullValue()).body("[0].email", org.hamcrest.core.Is.is(user.getEmail())).body("[0].service_roles", org.hamcrest.Matchers.hasSize(1)).body("[0].service_roles[0].service.external_id", org.hamcrest.core.Is.is(serviceExternalId)).body("[0].service_roles[0].service.name", org.hamcrest.core.Is.is(service.getName())).body("[0].telephone_number", org.hamcrest.core.Is.is(user.getTelephoneNumber())).body("[0].otp_key", org.hamcrest.core.Is.is(user.getOtpKey())).body("[0].login_counter", org.hamcrest.core.Is.is(0)).body("[0].disabled", org.hamcrest.core.Is.is(false)).body("[0].service_roles[0].role.name", org.hamcrest.core.Is.is(role.getName())).body("[0].service_roles[0].role.description", org.hamcrest.core.Is.is(role.getDescription())).body("[0].service_roles[0].role.permissions", org.hamcrest.Matchers.hasSize(role.getPermissions().size())).body("[0]._links", org.hamcrest.Matchers.hasSize(1)).body("[0]._links[0].href", org.hamcrest.core.Is.is("http://localhost:8080/v1/api/users/" + user.getExternalId())).body("[0]._links[0].method", org.hamcrest.core.Is.is("GET")).body("[0]._links[0].rel", org.hamcrest.core.Is.is("self")).body("size()", org.hamcrest.core.Is.is(1));
    }

    @org.junit.jupiter.api.Test
    public void shouldReturnEmptyResponse_whenGetUsers_withNonExistentExternalIds() {
        givenSetup().when().accept(io.restassured.http.ContentType.JSON).get(uk.gov.pay.adminusers.resources.UserResource.USERS_RESOURCE + "?ids=NON-EXISTENT-USER,ANOTHER_NON_EXISTENT_USER").then().statusCode(200).body("size()", org.hamcrest.core.Is.is(0));
    }

    @org.junit.jupiter.api.Test
    public void shouldReturnPartialResponse_whenGetUsers_whereSomeNonExistentExternalIds() {
        java.lang.String gatewayAccount1 = java.lang.String.valueOf(org.apache.commons.lang3.RandomUtils.nextInt());
        java.lang.String gatewayAccount2 = java.lang.String.valueOf(org.apache.commons.lang3.RandomUtils.nextInt());
        uk.gov.pay.adminusers.model.Service service = uk.gov.pay.adminusers.fixtures.ServiceDbFixture.serviceDbFixture(databaseHelper).withGatewayAccountIds(gatewayAccount1, gatewayAccount2).insertService();
        uk.gov.pay.adminusers.model.Role role = uk.gov.pay.adminusers.fixtures.RoleDbFixture.roleDbFixture(databaseHelper).insertRole();
        java.lang.String username = uk.gov.pay.adminusers.app.util.RandomIdGenerator.randomUuid();
        java.lang.String email = username + "@example.com";
        uk.gov.pay.adminusers.model.User existingUser = uk.gov.pay.adminusers.fixtures.UserDbFixture.userDbFixture(databaseHelper).withServiceRole(service.getId(), role.getId()).withUsername(username).withEmail(email).insertUser();
        givenSetup().when().contentType(io.restassured.http.ContentType.JSON).accept(io.restassured.http.ContentType.JSON).get(((uk.gov.pay.adminusers.resources.UserResource.USERS_RESOURCE + "?ids=") + existingUser.getExternalId()) + ",NON-EXISTENT-USER").then().statusCode(200).body("[0].external_id", org.hamcrest.core.Is.is(existingUser.getExternalId())).body("[0].username", org.hamcrest.core.Is.is(existingUser.getUsername())).body("[0].password", org.hamcrest.Matchers.nullValue()).body("[0].email", org.hamcrest.core.Is.is(existingUser.getEmail())).body("[0].service_roles", org.hamcrest.Matchers.hasSize(1)).body("[0].service_roles[0].service.external_id", org.hamcrest.core.Is.is(service.getExternalId())).body("[0].service_roles[0].service.name", org.hamcrest.core.Is.is(service.getName())).body("[0].telephone_number", org.hamcrest.core.Is.is(existingUser.getTelephoneNumber())).body("[0].otp_key", org.hamcrest.core.Is.is(existingUser.getOtpKey())).body("[0].login_counter", org.hamcrest.core.Is.is(0)).body("[0].disabled", org.hamcrest.core.Is.is(false)).body("[0].service_roles[0].role.name", org.hamcrest.core.Is.is(role.getName())).body("[0].service_roles[0].role.description", org.hamcrest.core.Is.is(role.getDescription())).body("[0].service_roles[0].role.permissions", org.hamcrest.Matchers.hasSize(role.getPermissions().size())).body("[0]._links", org.hamcrest.Matchers.hasSize(1)).body("[0]._links[0].href", org.hamcrest.core.Is.is("http://localhost:8080/v1/api/users/" + existingUser.getExternalId())).body("[0]._links[0].method", org.hamcrest.core.Is.is("GET")).body("[0]._links[0].rel", org.hamcrest.core.Is.is("self")).body("size()", org.hamcrest.core.Is.is(1));
    }
}
