package se.kth.models;

public enum FailureCategory {
    JAVA_VERSION_FAILURE,
    TEST_FAILURE,
    WERROR_FAILURE,
    COMPILATION_FAILURE,
    BUILD_SUCCESS,
    ENFORCER_FAILURE,
    DEPENDENCY_RESOLUTION_FAILURE,
    DEPENDENCY_LOCK_FAILURE,
    NO_DIFF,
    SPOON_FAILURE,
    UNKNOWN_FAILURE,
    TRANSFORMATION_FAILURE,
    MODEL_FAILURE,
    FAILURE_JAVADOC_GENERATION
}

