package github.chains;

import com.github.javaparser.ast.visitor.ModifierVisitor;
import com.github.javaparser.ast.stmt.ExpressionStmt;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.ast.expr.ArrayCreationExpr;
import com.github.javaparser.ast.expr.FieldAccessExpr;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.type.ClassOrInterfaceType;

/**
 * Generic JavaParser transformation rule to fix breaking changes in asto-core Content.From constructor.
 * 
 * This transformation fixes the issue where Content.From(byte[]) constructor was changed to Content.From(long, Publisher)
 * in asto-core v1.15.0.
 * 
 * The transformation:
 * 1. Identifies all usages of Content.From(byte[]) constructor
 * 2. Replaces them with Content.From(bytes.length, new io.reactivex.Flowable.just(bytes))
 * 
 * This rule is generic and can be applied to any project that uses asto-core.
 */
public class Main {
    
    public static void main(String[] args) throws Exception {
        // This is a template for the transformation rule
        // The actual implementation would be generated by JavaParser
    }
    
    public static class ContentFromFixer extends ModifierVisitor<Void> {
        
        @Override
        public ExpressionStmt visit(ExpressionStmt stmt, Void arg) {
            if (stmt.getExpression() instanceof ObjectCreationExpr) {
                ObjectCreationExpr expr = (ObjectCreationExpr) stmt.getExpression();
                if (isContentFromByteConstructor(expr)) {
                    // Transform the Content.From(byte[]) to Content.From(long, Publisher)
                    return transformContentFromByteConstructor(stmt, expr);
                }
            }
            return super.visit(stmt, arg);
        }
        
        /**
         * Check if this is a Content.From constructor call with a byte[] argument
         */
        private boolean isContentFromByteConstructor(ObjectCreationExpr expr) {
            // Check if it's a constructor for Content.From
            if (expr.getType() instanceof ClassOrInterfaceType) {
                ClassOrInterfaceType type = (ClassOrInterfaceType) expr.getType();
                if ("Content".equals(type.getNameAsString()) && 
                    expr.getArguments().size() == 1) {
                    // Check if the argument is a byte[] array creation
                    return expr.getArguments().get(0) instanceof ArrayCreationExpr && 
                           ((ArrayCreationExpr) expr.getArguments().get(0)).getElementType().toString().equals("byte");
                }
            }
            return false;
        }
        
        /**
         * Transform Content.From(byte[]) to Content.From(bytes.length, new io.reactivex.Flowable.just(bytes))
         */
        private ExpressionStmt transformContentFromByteConstructor(ExpressionStmt stmt, ObjectCreationExpr expr) {
            // Get the byte[] array argument
            ArrayCreationExpr arrayExpr = (ArrayCreationExpr) expr.getArguments().get(0);
            
            // Create the new arguments:
            // 1. bytes.length
            FieldAccessExpr lengthExpr = new FieldAccessExpr(arrayExpr, "length");
            
            // 2. new io.reactivex.Flowable.just(bytes)
            MethodCallExpr flowableJust = new MethodCallExpr();
            flowableJust.setScope(new NameExpr("io.reactivex.Flowable"));
            flowableJust.setName("just");
            flowableJust.addArgument(arrayExpr);
            
            // Create the new Content.From constructor call
            ObjectCreationExpr newExpr = new ObjectCreationExpr();
            newExpr.setType("com.artipie.asto.Content.From");
            newExpr.addArgument(lengthExpr);
            newExpr.addArgument(flowableJust);
            
            // Replace the old expression with the new one
            return new ExpressionStmt(newExpr);
        }
    }
}