package github.chains.spoonanalyzer.model;

public enum ConstructType {
    METHOD_INVOCATION,
    CONSTRUCTOR_CALL,
    FIELD_ACCESS,
    TYPE_REFERENCE,
    ANNOTATION_USAGE,
    IMPORT,
    LAMBDA,
    METHOD_REFERENCE,
    TYPE_CAST,
    ARRAY_ACCESS,
    ENUM_VALUE,
    VARIABLE_ACCESS,
    PACKAGE_REFERENCE,
    ARRAY_TYPE_REFERENCE,
    WILDCARD_REFERENCE,
    TYPE_PARAMETER_REFERENCE,
    // Additional types for completeness
    CAST,
    CATCH,
    THROW,
    LOCAL_VARIABLE,
    PARAMETER,
    TYPE_PARAMETER,
    ARRAY_TYPE,
    WILDCARD_TYPE,
    CLASS_DECLARATION,
    INTERFACE_DECLARATION,
    ENUM_DECLARATION
}

