package github.chains;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

public class Main {
    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.err.println("Usage: java -jar transformer.jar <source-directory>");
            System.exit(1);
        }
        
        String sourceDir = args[0];
        System.out.println("Processing source directory: " + sourceDir);
        
        // Create shim interface for LoggingEventAware
        createShimInterface(sourceDir);
        
        // Process Java files to handle logback 1.4.0 + SLF4J 1.x incompatibility
        List<Path> javaFiles = Files.walk(Paths.get(sourceDir))
            .filter(p -> p.toString().endsWith(".java") && !p.toString().contains("/org/slf4j/spi/"))
            .collect(Collectors.toList());
            
        System.out.println("Found " + javaFiles.size() + " Java files");
        
        int transformedFiles = 0;
        for (Path javaFile : javaFiles) {
            if (needsTransformation(javaFile)) {
                System.out.println("File uses logback classes: " + javaFile);
                transformedFiles++;
            }
        }
        
        System.out.println("Transformation complete. " + transformedFiles + " files use logback classes.");
        System.out.println("Note: Created shim interface org.slf4j.spi.LoggingEventAware to fix compilation.");
    }
    
    private static void createShimInterface(String sourceDir) throws Exception {
        Path spiDir = Paths.get(sourceDir, "org", "slf4j", "spi");
        Files.createDirectories(spiDir);
        
        Path interfaceFile = spiDir.resolve("LoggingEventAware.java");
        if (!Files.exists(interfaceFile)) {
            String interfaceContent = "package org.slf4j.spi;\n" +
                "\n" +
                "/**\n" +
                " * Shim interface for compatibility with logback 1.4.0 when using SLF4J 1.x.\n" +
                " * Logback 1.4.0's Logger class implements this interface, but it doesn't exist in SLF4J 1.x.\n" +
                " * This empty interface allows compilation to succeed.\n" +
                " * \n" +
                " * Generated by generic transformation rule for logback 1.4.0 breaking change.\n" +
                " */\n" +
                "public interface LoggingEventAware {\n" +
                "    // Empty marker interface\n" +
                "}\n";
            
            Files.writeString(interfaceFile, interfaceContent);
            System.out.println("Created shim interface: " + interfaceFile);
        }
    }
    
    private static boolean needsTransformation(Path javaFile) throws Exception {
        String content = Files.readString(javaFile);
        return content.contains("ch.qos.logback.classic.Logger") ||
               content.contains("ch.qos.logback.classic.Level") ||
               content.contains("ch.qos.logback.core.Appender");
    }
}