/*  */
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.04.29 at 03:07:27 AM UTC
// 
@XmlSchema(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.04_01", elementFormDefault = XmlNsForm.QUALIFIED)
package com.premiumminds.billy.portugal.services.export.saftpt.v1_04_01.schema;


import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;

